#!/bin/bash
#$ -cwd
#$ -l mem_requested=128G,h_rt=96:00:00
#$ -N scPagwas-2a-jobRun
#$ -j y
#$ -o logs/scPagwas-2a-jobRun.20241119.log
#$ -m beas
#$ -M p.allen@garvan.org.au
#$ -t 1-2

# Load conda env
source /home/petall/.bashrc
conda activate scPagwas

# Parallelisation bug fix
export OPENBLAS_NUM_THREADS=1

# Script
case "$SGE_TASK_ID" in
    1)
        Rscript src/scPagwas-2b-scriptRun.R reactome
        ;;
    2)
        Rscript src/scPagwas-2b-scriptRun.R kegg
        ;;
esac

# # Plot Results
# Rscript /g/data/ei56/pa3687/ILD_scLinker/code/scPagwas-3-plotting.R /g/data/ei56/pa3687/ILD_scLinker/output/scpagwas_reactome_IPF_bothsex_gbmi-allen2020.rds /g/data/ei56/pa3687/ILD_scLinker/scpagwas_reactome_IPF_bothsex_gbmi-allen2020
